name: iOS CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: SequisImage

    steps:
      - uses: actions/checkout@v4

      - name: Set Default Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project SequisImage.xcodeproj

      - name: Build
        run: |
          xcodebuild clean build \
            -project SequisImage.xcodeproj \
            -scheme SequisImage \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO
